### ISSUE TITLE
multiple install failing due to global env installs

### ISSUE THREAD

**Issue by wassfila** [TheSoundOfAIOSR/project_common#42]
- installing a first repo instance runs fine
- installing a second repo instance runs fine
- going back to the first fails

Prio is to document how to workaround this issue, then secondary step is to fix depending on effort
- [ ] document limitation of restricting to a single repo
- [ ] document how to clean up, automatically with a script or manually, which files should be deleted

Then if possible
- [ ] move any global install to the venv local directory so that it's enough to delete the venv or the repo to clean eveything
- [ ] or potentially keep the global install as separate step done by the user like install of csound as example

```
Successfully installed en-core-web-lg-2.3.1
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\tts_websocketserver\src\tts_websocketserver\initialize.py", line 4, in <module>
    get_pipeline().build()
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\tts_websocketserver\src\tts_websocketserver\..\..\..\tts_pipeline\src\tts_pipeline\pipelines\waterfall\pipeline.py", line 126, in build
    self.embedder.build()
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\tts_websocketserver\src\tts_websocketserver\..\..\..\tts_pipeline\src\tts_pipeline\pipelines\waterfall\models\gnews_models.py", line 9, in build
    self.model = hub.load(self.tf_hub_url)
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow_hub\module_v2.py", line 106, in load
    obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 859, in load
    return load_internal(export_dir, tags, options)["root"]
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 871, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "D:\Dev\SoundHacking\test\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: C:\Users\User\AppData\Local\Temp\tfhub_modules\510580b203329a4a95dfdfefd838bdcd202f0d13/{saved_model.pbtxt|saved_model.pb}
```

**Comment by wassfila** [comment]
first info about limitation done with #43

**Comment by wassfila** [comment]
as workaround delete the directory `C:\Users\User\AppData\Local\Temp\tfhub_modules` seems to fix the issue, at least I could proceed with the setup without the error

**Comment by Leofltt** [comment]
As a consequence of the current PR work on TTS ( #56 ) I have not been experiencing this issue anymore so far. More soak is required, but if we can confirm that the issue is now solved we might be able to close
